### ISSUE TITLE
Please publish _check_munkireport_link

### ISSUE THREAD

**Issue by sphen13** [sphen13/watchman-monitoring-plugins#12]
hey @watchmanpluginteam please send this plugin to all of my clients `_check_munkireport_link.plugin`

![2019-02-25_17-31-51](https://user-images.githubusercontent.com/46463190/53376262-5c7f5c80-3923-11e9-907b-8b206bec3ecc.png)

**Comment by watchmanpluginteam** [comment]
This was handled some time ago, but we didn't close the issue.
