### ISSUE TITLE
set the preferences, if they don't exist

### ISSUE THREAD

**Issue by YesThatAllen** [sphen13/watchman-monitoring-plugins#2]
I get the following notice when running the plugin

```
/Library/MonitoringClient/Plugins/_check_timedrift.plugin: line 8: settings_plist: command not found
2017-02-23 12:17:33.047 defaults[52539:20377218] 
The domain/default pair of (/Library/MonitoringClient/PluginSupport/_check_timedrift.plist, ntpServer) does not exist
2017-02-23 12:17:33.071 defaults[52540:20377222] 
The domain/default pair of (/Library/MonitoringClient/PluginSupport/_check_timedrift.plist, secondsOfAcceptableDrift) does not exist
```

This can be resolved by adding a check to the start of the plugin which looks for the settings plist, and creates it if it's not there.

Adding this key at that time will allow the plugin to show in the PreferencePane

```
	'PrefPaneVisibility'         : True
```

**Comment by sphen13** [comment]
yes ok - that error should be on stderr - but i agree i can create the file if it is not there.

as far as the second thing there - you mean i shoudl add a key value pair in the /Library/MonitoringClient/PluginSupport/_check_timedrift.plist of PrefPaneVisibility->True ?

**Comment by YesThatAllen** [comment]
yes, setting defaults is good, prevents that error, and solves the preferencepane bit

**Comment by sphen13** [comment]
ok - think i got that all addressed - a little clunky with bash and my brain - but seems to work well...

**Comment by YesThatAllen** [comment]
Addressed in https://github.com/sphen13/watchman-monitoring-plugins/commit/af07d6afabaf2cf24369d532e98e5c0cd7314f05
